language: php
sudo: true

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - ./bin/install-libsodium.sh
  - ./bin/fix-env-vars.sh
  - composer self-update
  - composer install --prefer-source --no-ansi --no-interaction

script: phpunit

after_script:
  - php vendor/bin/coveralls -v
