language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: 7.0
    - php: 7.1
    - php: hhvm

cache:
  directories:
    - $HOME/libsodium
    - vendor

addons:
  apt:
    packages:
    - curl
    - openssl

before_script:
  - composer selfupdate
  - sed -i s#\>=5.5#\>=5.3.0#g composer.json
  - ./bin/install-dependencies.sh
  - composer install --prefer-source --no-ansi --no-interaction

script: phpunit

after_script:
  - php vendor/bin/coveralls -v
