language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - ./bin/install-dependencies.sh
  - composer install --prefer-source --no-ansi --no-interaction

cache:
  directories:
    - $HOME/libsodium
    - vendor

script: phpunit

after_script:
  - php vendor/bin/coveralls -v

